### ISSUE TITLE
登入頁輸入錯誤帳號 

### ISSUE THREAD

**Issue by kuangtsao** [kuangtsao/twitter-fullstack-2020#8]
期待行為：應跳回錯誤頁
現在行為：會不斷的轉圈並跳錯誤訊息
```
Executing (default): SELECT `id`, `name`, `email`, `password`, `avatar`, `account`, `cover`, `introduction`, `role`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`account` = '999' LIMIT 1;
(node:16696) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'role' of null
    at /home/lmarcus/code/alphacamp/twitter-fullstack-2020/config/passport.js:19:43
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kuangtsao** [comment]
https://github.com/kuangtsao/twitter-fullstack-2020/blob/master/config/passport.js

**Comment by kuangtsao** [comment]
目前情況
當輸入不存在帳號或者 email 時，取到的 `user` 會是 null 導致觸發不了錯誤訊息

```
    (req, account, password, cb) => {
      User.findOne({ where: { account } }).then(user => {
        // 後台登入限制
        if (req.url === '/admin/signin' && user.role === false) {
          return cb(null, false, req.flash('error_messages', '查無此帳號！'))
        }
        // 前台登入限制
        if (req.url === '/signin' && user.role === true) {
          return cb(null, false, req.flash('error_messages', '查無此帳號！'))
        }
        if (!user) { return cb(null, false, req.flash('error_messages', '查無此帳號！')) }
        bcrypt.compare(password, user.password).then(res => {
          if (!res) {
            return cb(
              null,
              false,
              req.flash('error_messages', '密碼輸入錯誤！')
            )
          }
          return cb(null, user)
        })
      })
```

**Comment by kuangtsao** [comment]
已修復
